import json, re, csv, os, collections, html, difflib

DATA = os.path.dirname(os.path.abspath(__file__))
def p(name): return os.path.join(DATA, name)

IN = p("2026-07-07_kamsi_req5_bulk_products_v2.jsonl")

products = {}
order = []

with open(IN, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        parent = obj.get("__parentId")
        if parent is None:
            gid = obj["id"]
            products[gid] = {
                "legacyResourceId": obj["legacyResourceId"],
                "handle": obj["handle"],
                "onlineStoreUrl": obj.get("onlineStoreUrl") or "",
                "title": obj["title"],
                "descriptionHtml": obj.get("descriptionHtml") or "",
                "productType": (obj.get("productType") or "").strip(),
                "tags": obj.get("tags") or [],
                "updatedAt": obj.get("updatedAt") or "",
                "seoTitle": (obj.get("seo") or {}).get("title") or "",
                "seoDescription": (obj.get("seo") or {}).get("description") or "",
                "collections": [],
            }
            order.append(gid)
        else:
            prod = products.get(parent)
            if prod is not None and "title" in obj:
                prod["collections"].append(obj["title"])

print("total products:", len(products))

# ================== Normalization helpers (per GPT spec) ==================
TAG_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")
CODE_SUFFIX_RES = [
    re.compile(r"\s*[~#]\s*\d+\s*$"),          # ~2801  #2801
    re.compile(r"\s*-\s*\d+\s*$"),              # - 2801 / -2801
    re.compile(r"\s*\|\s*\d+\s*$"),             # | 2801
    re.compile(r"\s+(sku|code)\s*\d+\s*$", re.IGNORECASE),  # sku 2801 / code 2801
]
PUNCT_RUN_RE = re.compile(r"([-|~#])\1+")
PUNCT_SPACING_RE = re.compile(r"\s*([-|~])\s*")

SEO_INTENT_WORDS = ["buy", "shop", "online", "uk", "sale", "best", "premium", "led", "lighting", "lights", "ledsone"]


def strip_html(s):
    return TAG_RE.sub(" ", s or "")


def normalize_text(s):
    """normalizeText(value): null->'', strip HTML, decode entities, lowercase, trim,
    collapse whitespace, normalize punctuation spacing/repeats. Does NOT strip SKU suffix."""
    if s is None:
        return ""
    s = strip_html(s)
    s = html.unescape(s)
    s = s.lower()
    s = WS_RE.sub(" ", s).strip()
    s = PUNCT_RUN_RE.sub(r"\1", s)
    s = PUNCT_SPACING_RE.sub(r" \1 ", s)
    s = WS_RE.sub(" ", s).strip()
    return s


def strip_trailing_code(s):
    """Remove trailing SKU/code suffix patterns (~2801, -2801, |2801, #2801, sku 2801, code 2801)."""
    prev = None
    cur = s
    while prev != cur:
        prev = cur
        for rx in CODE_SUFFIX_RES:
            cur = rx.sub("", cur).strip()
    return cur


def normalize_full(s):
    """normalizeText + trailing SKU/code suffix removal (used for title comparisons)."""
    return strip_trailing_code(normalize_text(s))


def similarity(a, b):
    if not a or not b:
        return 0.0
    return difflib.SequenceMatcher(None, a, b).ratio()


def has_seo_wording(norm_text):
    return any(w in norm_text.split() or w in norm_text for w in SEO_INTENT_WORDS)


# ================== isAutoGeneratedTitle ==================
def title_status(product_title, meta_title_raw):
    mt_raw = (meta_title_raw or "").strip()
    if not mt_raw:
        return "Missing"

    pt_norm_full = normalize_text(product_title)          # normalized, no SKU strip
    mt_norm_full = normalize_text(mt_raw)                  # normalized, no SKU strip
    pt_norm_code = normalize_full(product_title)            # normalized + SKU-suffix stripped
    mt_norm_code = normalize_full(mt_raw)                    # normalized + SKU-suffix stripped (meta rarely has one, harmless)

    # 2. exact normalized match
    if mt_norm_full == pt_norm_full:
        return "Auto-generated"
    # 3/4. equal after normalization + SKU/code suffix removed (the core reported bug)
    if pt_norm_code == mt_norm_code and pt_norm_code != "":
        return "Auto-generated"
    # 5. meta title is a prefix/truncated version of the (SKU-stripped) product title
    if pt_norm_code and mt_norm_code and pt_norm_code.startswith(mt_norm_code) and len(mt_norm_code) >= 0.8 * len(pt_norm_code):
        return "Auto-generated"
    # 6. very high similarity with no unique SEO wording added
    sim = similarity(pt_norm_code, mt_norm_code)
    if sim >= 0.90 and not has_seo_wording(mt_norm_full):
        return "Auto-generated"
    return "Custom"


# ================== isAutoGeneratedDescription ==================
def description_status(product_desc_html, meta_desc_raw):
    md_raw = (meta_desc_raw or "").strip()
    if not md_raw:
        return "Missing"

    pd_norm = normalize_text(product_desc_html)
    md_norm = normalize_text(md_raw)

    # 2. exact normalized match
    if md_norm == pd_norm:
        return "Auto-generated"
    # 3. product description starts with the meta description (prefix/truncated copy)
    if pd_norm and md_norm and pd_norm.startswith(md_norm) and len(md_norm) >= 20:
        return "Auto-generated"
    # 4. meta description is the first 150-170 characters of the product description
    for n in (150, 155, 160, 165, 170):
        if md_norm == pd_norm[:n].strip():
            return "Auto-generated"
    # 5. very high similarity, no unique SEO wording
    sim = similarity(pd_norm, md_norm)
    if sim >= 0.90 and not has_seo_wording(md_norm):
        return "Auto-generated"
    return "Custom"


def collection_type(prod):
    if prod["productType"]:
        return prod["productType"]
    if prod["collections"]:
        return prod["collections"][0]
    if prod["tags"]:
        return prod["tags"][0]
    return "Not Available"


rows = []
title_status_counts = collections.Counter()
desc_status_counts = collections.Counter()
action_counts = collections.Counter()

for gid in order:
    r = products[gid]
    desc_text = normalize_text(r["descriptionHtml"]) and strip_html(r["descriptionHtml"])
    desc_display = WS_RE.sub(" ", strip_html(r["descriptionHtml"])).strip()

    ts = title_status(r["title"], r["seoTitle"])
    ds = description_status(r["descriptionHtml"], r["seoDescription"])
    title_status_counts[ts] += 1
    desc_status_counts[ds] += 1

    title_bad = ts in ("Missing", "Auto-generated")
    desc_bad = ds in ("Missing", "Auto-generated")

    if title_bad and desc_bad:
        action = "Add Custom Meta Title and Meta Description"
    elif title_bad:
        action = "Add Custom Meta Title"
    elif desc_bad:
        action = "Add Custom Meta Description"
    else:
        action = "OK"
    action_counts[action] += 1

    seo_title_raw = r["seoTitle"].strip()
    seo_desc_raw = r["seoDescription"].strip()

    rows.append({
        "page_url": "/products/%s" % r["handle"],
        "collection_type": collection_type(r),
        "product_title": r["title"],
        "product_description": desc_display,
        "meta_title": seo_title_raw,
        "meta_description": seo_desc_raw,
        "title_length": len(seo_title_raw),
        "description_length": len(seo_desc_raw),
        "meta_title_status": ts,
        "meta_description_status": ds,
        "last_updated": r["updatedAt"],
        "action_needed": action,
    })

print("Meta Title Status  ->", dict(title_status_counts))
print("Meta Desc Status   ->", dict(desc_status_counts))
print("Action Needed      ->", dict(action_counts))

# ================== Validation: known test case ==================
test_product_title = "1 Outlet French Gold Metal Ceiling Rose 120x25mm~2801"
test_meta_title = "1 Outlet French Gold Metal Ceiling Rose 120x25mm"
test_result = title_status(test_product_title, test_meta_title)
print("\n--- KNOWN TEST CASE ---")
print("Product Title:", test_product_title)
print("Meta Title:   ", test_meta_title)
print("Result:", test_result, "(expected: Auto-generated)")
assert test_result == "Auto-generated", "VALIDATION FAILED — known test case did not produce Auto-generated"
print("VALIDATION PASSED")

# ================== Save CSV + JSON ==================
OUT_CSV = p("2026-07-08_kamsi_req5_missing_meta_log_v2.csv")
with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["page_url", "collection_type", "product_title", "product_description",
                "meta_title", "meta_description", "title_length", "description_length",
                "meta_title_status", "meta_description_status", "last_updated", "action_needed"])
    for r in rows:
        w.writerow([r["page_url"], r["collection_type"], r["product_title"], r["product_description"][:500],
                    r["meta_title"], r["meta_description"], r["title_length"], r["description_length"],
                    r["meta_title_status"], r["meta_description_status"], r["last_updated"], r["action_needed"]])
print("wrote CSV:", OUT_CSV)

OUT_JSON = p("2026-07-08_kamsi_req5_rows_v2.json")
json.dump(rows, open(OUT_JSON, "w", encoding="utf-8"))
print("wrote JSON:", OUT_JSON, "rows:", len(rows))

total = len(rows)
missing_title_n = sum(1 for r in rows if r["meta_title_status"] == "Missing")
auto_title_n = sum(1 for r in rows if r["meta_title_status"] == "Auto-generated")
missing_desc_n = sum(1 for r in rows if r["meta_description_status"] == "Missing")
auto_desc_n = sum(1 for r in rows if r["meta_description_status"] == "Auto-generated")
ok_n = sum(1 for r in rows if r["action_needed"] == "OK")
print("\nKPIs -> total: %d, missing title: %d, auto title: %d, missing desc: %d, auto desc: %d, OK: %d" % (
    total, missing_title_n, auto_title_n, missing_desc_n, auto_desc_n, ok_n))
